OPENAI_API_KEY = "sk-proj-eU8AQxYeo3NYuoeM4saFT3BlbkFJpMm1rU6G3naRsI4ZyODu"
QDRANT_URL = 'https://7e7cb9d5-f149-4a0a-9c39-b48876400895.us-east4-0.gcp.cloud.qdrant.io:6333'
QDRANT_API_KEY = 'qafJOJIez7XR-9gfDc7PhGjBzFrFttGT84XyRU0WlsbulSanFUZbGw'
GOOGLE_API_KEY = "AIzaSyA0q3l0mqtGrBxiFwvy77i1tyiG3yB--Qs"